const std = @import("std");

// Generated by tools/woff2_table_gen/gen_tables.py from vendor/brotli-decompressor/src/transform.rs. Do not hand-edit.

pub const kIdentity: u8 = 0;
pub const kOmitLast1: u8 = 1;
pub const kOmitLast2: u8 = 2;
pub const kOmitLast3: u8 = 3;
pub const kOmitLast4: u8 = 4;
pub const kOmitLast5: u8 = 5;
pub const kOmitLast6: u8 = 6;
pub const kOmitLast7: u8 = 7;
pub const kOmitLast8: u8 = 8;
pub const kOmitLast9: u8 = 9;
pub const kUppercaseFirst: u8 = 10;
pub const kUppercaseAll: u8 = 11;
pub const kOmitFirst1: u8 = 12;
pub const kOmitFirst2: u8 = 13;
pub const kOmitFirst3: u8 = 14;
pub const kOmitFirst4: u8 = 15;
pub const kOmitFirst5: u8 = 16;
pub const kOmitFirst6: u8 = 17;
pub const kOmitFirst7: u8 = 18;
pub const kOmitFirst9: u8 = 20;
pub const kPFix_EMPTY: u8 = 0;
pub const kPFix_SP: u8 = 1;
pub const kPFix_COMMASP: u8 = 3;
pub const kPFix_SPofSPtheSP: u8 = 6;
pub const kPFix_SPtheSP: u8 = 9;
pub const kPFix_eSP: u8 = 12;
pub const kPFix_SPofSP: u8 = 15;
pub const kPFix_sSP: u8 = 20;
pub const kPFix_DOT: u8 = 23;
pub const kPFix_SPandSP: u8 = 25;
pub const kPFix_SPinSP: u8 = 31;
pub const kPFix_DQUOT: u8 = 36;
pub const kPFix_SPtoSP: u8 = 38;
pub const kPFix_DQUOTGT: u8 = 43;
pub const kPFix_NEWLINE: u8 = 46;
pub const kPFix_DOTSP: u8 = 48;
pub const kPFix_CLOSEBR: u8 = 51;
pub const kPFix_SPforSP: u8 = 53;
pub const kPFix_SPaSP: u8 = 59;
pub const kPFix_SPthatSP: u8 = 63;
pub const kPFix_SQUOT: u8 = 70;
pub const kPFix_SPwithSP: u8 = 72;
pub const kPFix_SPfromSP: u8 = 79;
pub const kPFix_SPbySP: u8 = 86;
pub const kPFix_OPEN: u8 = 91;
pub const kPFix_DOTSPTheSP: u8 = 93;
pub const kPFix_SPonSP: u8 = 100;
pub const kPFix_SPasSP: u8 = 105;
pub const kPFix_SPisSP: u8 = 110;
pub const kPFix_ingSP: u8 = 115;
pub const kPFix_NEWLINETAB: u8 = 120;
pub const kPFix_COLON: u8 = 123;
pub const kPFix_edSP: u8 = 125;
pub const kPFix_EQDQUOT: u8 = 129;
pub const kPFix_SPatSP: u8 = 132;
pub const kPFix_lySP: u8 = 137;
pub const kPFix_COMMA: u8 = 141;
pub const kPFix_EQSQUOT: u8 = 143;
pub const kPFix_DOTcomSLASH: u8 = 146;
pub const kPFix_DOTSPThisSP: u8 = 152;
pub const kPFix_SPnotSP: u8 = 160;
pub const kPFix_erSP: u8 = 166;
pub const kPFix_alSP: u8 = 170;
pub const kPFix_fulSP: u8 = 174;
pub const kPFix_iveSP: u8 = 179;
pub const kPFix_lessSP: u8 = 184;
pub const kPFix_estSP: u8 = 190;
pub const kPFix_izeSP: u8 = 195;
pub const kPFix_NBSP: u8 = 200;
pub const kPFix_ousSP: u8 = 203;

pub const Transform = struct {
    prefix_id: u8,
    transform: u8,
    suffix_id: u8,
};

pub const prefix_suffix: [208]u8 = [_]u8{
    0x00, 0x20, 0x00, 0x2c, 0x20, 0x00, 0x20, 0x6f, 0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x00, 0x20,
    0x6f, 0x66, 0x20, 0x00, 0x73, 0x20, 0x00, 0x2e, 0x00, 0x20, 0x61, 0x6e, 0x64, 0x20, 0x00, 0x20,
    0x69, 0x6e, 0x20, 0x00, 0x22, 0x00, 0x20, 0x74, 0x6f, 0x20, 0x00, 0x22, 0x3e, 0x00, 0x0a, 0x00,
    0x2e, 0x20, 0x00, 0x5d, 0x00, 0x20, 0x66, 0x6f, 0x72, 0x20, 0x00, 0x20, 0x61, 0x20, 0x00, 0x20,
    0x74, 0x68, 0x61, 0x74, 0x20, 0x00, 0x27, 0x00, 0x20, 0x77, 0x69, 0x74, 0x68, 0x20, 0x00, 0x20,
    0x66, 0x72, 0x6f, 0x6d, 0x20, 0x00, 0x20, 0x62, 0x79, 0x20, 0x00, 0x28, 0x00, 0x2e, 0x20, 0x54,
    0x68, 0x65, 0x20, 0x00, 0x20, 0x6f, 0x6e, 0x20, 0x00, 0x20, 0x61, 0x73, 0x20, 0x00, 0x20, 0x69,
    0x73, 0x20, 0x00, 0x69, 0x6e, 0x67, 0x20, 0x00, 0x0a, 0x09, 0x00, 0x3a, 0x00, 0x65, 0x64, 0x20,
    0x00, 0x3d, 0x22, 0x00, 0x20, 0x61, 0x74, 0x20, 0x00, 0x6c, 0x79, 0x20, 0x00, 0x2c, 0x00, 0x3d,
    0x27, 0x00, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x00, 0x2e, 0x20, 0x54, 0x68, 0x69, 0x73, 0x20, 0x00,
    0x20, 0x6e, 0x6f, 0x74, 0x20, 0x00, 0x65, 0x72, 0x20, 0x00, 0x61, 0x6c, 0x20, 0x00, 0x66, 0x75,
    0x6c, 0x20, 0x00, 0x69, 0x76, 0x65, 0x20, 0x00, 0x6c, 0x65, 0x73, 0x73, 0x20, 0x00, 0x65, 0x73,
    0x74, 0x20, 0x00, 0x69, 0x7a, 0x65, 0x20, 0x00, 0xc2, 0xa0, 0x00, 0x6f, 0x75, 0x73, 0x20, 0x00,
};

pub const num_transforms: i32 = 121;

pub const transforms: [121]Transform = [_]Transform{
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst1, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPtheSP },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_sSP, .transform = kIdentity, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPofSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPandSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst2, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast1, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_COMMASP, .transform = kIdentity, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_COMMASP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPinSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPtoSP },
    .{ .prefix_id = kPFix_eSP, .transform = kIdentity, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_DQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_DOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_DQUOTGT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_NEWLINE },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast3, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_CLOSEBR },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPforSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst3, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast2, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPaSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPthatSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_DOTSP },
    .{ .prefix_id = kPFix_DOT, .transform = kIdentity, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_COMMASP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst4, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPwithSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPfromSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPbySP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst5, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst6, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_SPtheSP, .transform = kIdentity, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast4, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_DOTSPTheSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPonSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPasSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPisSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast7, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast1, .suffix_id = kPFix_ingSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_NEWLINETAB },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_COLON },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_DOTSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_edSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst9, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitFirst7, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast6, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_OPEN },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_COMMASP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast8, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPatSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_lySP },
    .{ .prefix_id = kPFix_SPtheSP, .transform = kIdentity, .suffix_id = kPFix_SPofSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast5, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kOmitLast9, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_COMMASP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_DQUOT },
    .{ .prefix_id = kPFix_DOT, .transform = kIdentity, .suffix_id = kPFix_OPEN },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_DQUOTGT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_EQDQUOT },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_DOT },
    .{ .prefix_id = kPFix_DOTcomSLASH, .transform = kIdentity, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_SPtheSP, .transform = kIdentity, .suffix_id = kPFix_SPofSPtheSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_SQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_DOTSPThisSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_COMMA },
    .{ .prefix_id = kPFix_DOT, .transform = kIdentity, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_OPEN },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_DOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_SPnotSP },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_EQDQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_erSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_SP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_alSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_EQSQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_DQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_DOTSP },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_OPEN },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_fulSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_DOTSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_iveSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_lessSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_SQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_estSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_DOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_DQUOTGT },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_EQSQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_COMMA },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_izeSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_DOT },
    .{ .prefix_id = kPFix_NBSP, .transform = kIdentity, .suffix_id = kPFix_EMPTY },
    .{ .prefix_id = kPFix_SP, .transform = kIdentity, .suffix_id = kPFix_COMMA },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_EQDQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_EQDQUOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kIdentity, .suffix_id = kPFix_ousSP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_COMMASP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseFirst, .suffix_id = kPFix_EQSQUOT },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_COMMA },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_EQDQUOT },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_COMMASP },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_COMMA },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_OPEN },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_DOTSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_DOT },
    .{ .prefix_id = kPFix_EMPTY, .transform = kUppercaseAll, .suffix_id = kPFix_EQSQUOT },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_DOTSP },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_EQDQUOT },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseAll, .suffix_id = kPFix_EQSQUOT },
    .{ .prefix_id = kPFix_SP, .transform = kUppercaseFirst, .suffix_id = kPFix_EQSQUOT },
};

